$ANSIBLE_VAULT;1.1;AES256
30386363316132333661336135303735373136386263666536613137613165316565653632383666
3037646631663166653161653666343939336430353664370a346531663166343431336335663134
63303731653138363238643461373134316166613930623330316436303531303462386361613562
3663346165356462350a383539393662613232336632646530626233333936656264616666326666
66343038646633316261373262616564636530386566613336343364313561623731383231306665
63623639336236333962646635336337643965656439633330313538373031313235323562333434
63343534616634623865326133366437643264643834343065353339326433666364383764376432
33636465393734343361623765633761326661353638353165303633363935363061323934363232
61663166376561613762353331383761366633336638613937653830626132383637383536396137
34646662353635356362613435376634383138666433626463613062653963333536386339623262
33613234313232666366343638333238656163653161316131336636336363376361333162356466
65346137663465353232386231656366383235353463343763613039303361363436343238643331
31316364623431363835646234373538356465373733393534633462353034616630613334373334
6361326464333934353335393366306662363533666636306135
