$ANSIBLE_VAULT;1.1;AES256
31326537646133396563633465623965653931613161306166653134306230303133366237326165
6633656563343064623538363936353335316338643366390a663563316230303565666536636463
38653431346433393664663634666131313939393630646266313461653464316238356633366561
3262366138616535650a306138303739316633666663653236646234663232336264386365356535
30313764393162316464633037363065373633363135363663353764613062396439666561386232
38336663633731643261646634333031663264353732336334646236366366363265386132323335
63386438303738643066633837393432323831383233656465623333313964303664633965303835
65336166633363336536373431383865363337623039396535326333666539396537383536356162
66353038396336653133383834623432656431396361613130383432646566323262393864313037
35313865393363616465633033306666633734336335633765353563613664383631356566356665
62333731623831666337386462373631386335323032323738343235363739373064303931643561
36393462643331353662376362323539316134346330386162386631636166303938366166373831
66656534316238323066366461666531663730626265373363633761303230353138363031393135
3134326561303133656439643132323566636663653962303261
